# Generated by Django 5.2.17 on 2026-09-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(max_length=80, verbose_name='小区名称')),
                ('region', models.CharField(max_length=40, verbose_name='所在区域')),
                ('layout', models.CharField(max_length=20, verbose_name='户型')),
                ('area', models.IntegerField(verbose_name='面积(㎡)')),
                ('rent', models.IntegerField(verbose_name='月租金')),
                ('deposit', models.IntegerField(verbose_name='押金')),
                ('payment', models.CharField(max_length=20, verbose_name='付款方式')),
                ('facilities', models.JSONField(blank=True, default=list, verbose_name='配套设施')),
                ('status', models.CharField(choices=[('待出租', '待出租'), ('已预约', '已预约'), ('已签约', '已签约')], default='待出租', max_length=20, verbose_name='房屋状态')),
                ('landlord_phone', models.CharField(blank=True, max_length=30, verbose_name='房东电话')),
            ],
            options={
                'verbose_name': '房屋',
                'verbose_name_plural': '房屋',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='租期开始')),
                ('end_date', models.DateField(verbose_name='租期结束')),
                ('status', models.CharField(choices=[('生效中', '生效中'), ('已到期', '已到期'), ('已终止', '已终止')], default='生效中', max_length=16, verbose_name='租约状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.house', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '租约',
                'verbose_name_plural': '租约',
                'ordering': ['-start_date'],
            },
        ),
    ]
