# Generated by Django 5.2.17 on 2026-09-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(choices=[('房东', '房东'), ('租客', '租客'), ('物业人员', '物业人员')], default='租客', max_length=20)),
                ('qualifications', models.JSONField(blank=True, default=list, help_text='物业人员可处理的故障类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
