"""报修闭环相关枚举值，统一维护。"""

# 用户角色
ROLE_LANDLORD = '房东'
ROLE_RESIDENT = '租客'
ROLE_STAFF = '物业人员'
USER_ROLES = (ROLE_LANDLORD, ROLE_RESIDENT, ROLE_STAFF)
ROLE_CHOICES = tuple((role, role) for role in USER_ROLES)

# 房屋状态
HOUSE_STATUS = ('待出租', '已预约', '已签约')
HOUSE_STATUS_CHOICES = tuple((status, status) for status in HOUSE_STATUS)

# 租约状态
LEASE_ACTIVE = '生效中'
LEASE_EXPIRED = '已到期'
LEASE_TERMINATED = '已终止'
LEASE_STATUS = (LEASE_ACTIVE, LEASE_EXPIRED, LEASE_TERMINATED)
LEASE_STATUS_CHOICES = tuple((status, status) for status in LEASE_STATUS)

# 故障类型
FAULT_PLUMBING_ELECTRIC = '水电'
FAULT_LOCK = '门锁'
FAULT_PIPE = '管道'
FAULT_APPLIANCE = '家电'
FAULT_OTHER = '其他'
REPAIR_TYPES = (FAULT_PLUMBING_ELECTRIC, FAULT_LOCK, FAULT_PIPE, FAULT_APPLIANCE, FAULT_OTHER)
FAULT_TYPE_CHOICES = tuple((fault, fault) for fault in REPAIR_TYPES)

# 工单状态
TICKET_PENDING = '待受理'
TICKET_PROCESSING = '处理中'
TICKET_COMPLETED = '已完成'
TICKET_STATUS = (TICKET_PENDING, TICKET_PROCESSING, TICKET_COMPLETED)
TICKET_STATUS_CHOICES = tuple((status, status) for status in TICKET_STATUS)
OPEN_TICKET_STATUS = (TICKET_PENDING, TICKET_PROCESSING)

# 处理轨迹动作
ACTION_CREATE = '提交'
ACTION_ACCEPT = '接单'
ACTION_TRANSFER = '转派'
ACTION_COMPLETE = '完工'
ACTIONS = (ACTION_CREATE, ACTION_ACCEPT, ACTION_TRANSFER, ACTION_COMPLETE)
ACTION_CHOICES = tuple((action, action) for action in ACTIONS)

# 接单时未指定预计上门时间的默认时长（小时）
DEFAULT_VISIT_WITHIN_HOURS = 24
