HOUSE_STATUS = ('待出租', '已预约', '已签约')
REPAIR_TYPES = ('水电', '门锁', '管道', '家电', '其他')
USER_ROLES = ('房东', '租客', '物业人员')

ROLE_LANDLORD, ROLE_TENANT, ROLE_STAFF = USER_ROLES

CONTRACT_STATUS = ('生效中', '已到期', '已终止')
CONTRACT_ACTIVE, CONTRACT_EXPIRED, CONTRACT_TERMINATED = CONTRACT_STATUS

REPAIR_STATUS = ('待接单', '处理中', '已完工')
STATUS_PENDING, STATUS_PROCESSING, STATUS_DONE = REPAIR_STATUS
REPAIR_OPEN_STATUS = (STATUS_PENDING, STATUS_PROCESSING)

REPAIR_ACTIONS = ('创建', '合并', '派单', '接单', '转派', '完工')
ACTION_CREATE, ACTION_MERGE, ACTION_DISPATCH, ACTION_ACCEPT, ACTION_REASSIGN, ACTION_COMPLETE = REPAIR_ACTIONS
